ALTER SESSION SET CONTAINER= XEPDB1;

CREATE USER CONSTRUCTION IDENTIFIED BY 123;
GRANT CREATE SESSION TO CONSTRUCTION;
GRANT UNLIMITED TABLESPACE TO CONSTRUCTION;
GRANT CREATE TABLE TO CONSTRUCTION;
GRANT CREATE SEQUENCE TO CONSTRUCTION;
GRANT CREATE VIEW TO CONSTRUCTION;
GRANT CREATE PROCEDURE TO CONSTRUCTION;
GRANT CREATE TRIGGER TO CONSTRUCTION;
GRANT EXECUTE ON DBMS_SCHEDULER TO CONSTRUCTION;
GRANT CREATE JOB TO CONSTRUCTION;